-- pgvector 익스텐션 활성화 (최초 1회)
CREATE EXTENSION IF NOT EXISTS vector;

-- =============================================
-- 분석 전 테이블 (mock 데이터 입력 대상)
-- =============================================

CREATE TABLE IF NOT EXISTS analysis_raw_transaction
(
    raw_transaction_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT         NOT NULL,
    source_type           VARCHAR(20)    NOT NULL, -- BANK / CARD / SECURITIES
    source_transaction_id BIGINT         NOT NULL,
    account_id            BIGINT,
    transaction_type      VARCHAR(50)    NOT NULL, -- INCOME / EXPENSE
    category              VARCHAR(100),
    amount                DECIMAL(18, 2) NOT NULL,
    balance_after         DECIMAL(18, 2),
    transaction_at        TIMESTAMP      NOT NULL,
    raw_payload           JSON           NOT NULL,
    synced_at             TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_asset_snapshot
(
    snapshot_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT         NOT NULL,
    total_asset            DECIMAL(18, 2) NOT NULL,
    total_bank_asset       DECIMAL(18, 2),
    total_stock_asset      DECIMAL(18, 2),
    emergency_fund_amount  DECIMAL(18, 2),
    emergency_fund_ratio   DECIMAL(5, 2),
    snapshot_at            TIMESTAMP      NOT NULL
);

-- =============================================
-- Python 통계 결과 테이블
-- =============================================

CREATE TABLE IF NOT EXISTS analysis_monthly_income
(
    monthly_income_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT         NOT NULL,
    year_month          VARCHAR(7)     NOT NULL, -- YYYY-MM
    UNIQUE (user_id, year_month),
    freelancer_income   DECIMAL(18, 2),
    salary_income       DECIMAL(18, 2),
    investment_income   DECIMAL(18, 2),
    etc_income          DECIMAL(18, 2),
    total_income        DECIMAL(18, 2) NOT NULL,
    income_growth_rate  DECIMAL(5, 2),
    analyzed_at         TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_monthly_expense
(
    monthly_expense_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT         NOT NULL,
    year_month             VARCHAR(7)     NOT NULL, -- YYYY-MM
    UNIQUE (user_id, year_month),
    food_expense           DECIMAL(18, 2),
    transport_expense      DECIMAL(18, 2),
    shopping_expense       DECIMAL(18, 2),
    housing_expense        DECIMAL(18, 2),
    communication_expense  DECIMAL(18, 2),
    medical_expense        DECIMAL(18, 2),
    investment_expense     DECIMAL(18, 2),
    subscription_expense   DECIMAL(18, 2),
    etc_expense            DECIMAL(18, 2),
    total_expense          DECIMAL(18, 2) NOT NULL,
    expense_growth_rate    DECIMAL(5, 2),
    analyzed_at            TIMESTAMP      NOT NULL
);

-- =============================================
-- LLM 분석 결과 테이블
-- =============================================

CREATE TABLE IF NOT EXISTS analysis_consumption_pattern
(
    pattern_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT        NOT NULL,
    consumption_type        VARCHAR(100)  NOT NULL,
    risk_score              DECIMAL(5, 2),
    fixed_expense_ratio     DECIMAL(5, 2),
    impulsive_expense_ratio DECIMAL(5, 2),
    luxury_expense_ratio    DECIMAL(5, 2),
    summary                 TEXT,
    analyzed_at             TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_ai_briefing_history
(
    briefing_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT        NOT NULL,
    briefing_type       VARCHAR(20)   NOT NULL, -- DAILY / WEEKLY / MONTHLY
    briefing_summary    TEXT          NOT NULL,
    generated_model     VARCHAR(100),
    created_at          TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS analysis_ai_recommendation
(
    recommendation_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT   NOT NULL,
    recommendation_type    VARCHAR(50) NOT NULL, -- SALARY / INVESTMENT / CONSUMPTION / STOCK
    recommendation_content TEXT     NOT NULL,
    applied_yn             BOOLEAN  NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP NOT NULL
);

-- =============================================
-- 임베딩 테이블 (BGE-M3 → pgvector)
-- =============================================

CREATE TABLE IF NOT EXISTS analysis_ai_vector_metadata
(
    vector_metadata_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT         NOT NULL,
    vector_type        VARCHAR(50)    NOT NULL,
    reference_id       BIGINT,
    embedding_version  VARCHAR(50),
    chunk_text         TEXT,
    vector_key         VARCHAR(255),
    embedding          vector(1024),  -- BGE-M3 출력 차원
    indexed_at         TIMESTAMP      NOT NULL
);

-- =============================================
-- 인덱스
-- =============================================

CREATE INDEX IF NOT EXISTS idx_raw_transaction_user_id ON analysis_raw_transaction (user_id);
CREATE INDEX IF NOT EXISTS idx_raw_transaction_transaction_at ON analysis_raw_transaction (transaction_at);

CREATE INDEX IF NOT EXISTS idx_asset_snapshot_user_id ON analysis_asset_snapshot (user_id);
CREATE INDEX IF NOT EXISTS idx_asset_snapshot_snapshot_at ON analysis_asset_snapshot (snapshot_at);

CREATE INDEX IF NOT EXISTS idx_monthly_income_user_id ON analysis_monthly_income (user_id);
CREATE INDEX IF NOT EXISTS idx_monthly_income_year_month ON analysis_monthly_income (year_month);

CREATE INDEX IF NOT EXISTS idx_monthly_expense_user_id ON analysis_monthly_expense (user_id);
CREATE INDEX IF NOT EXISTS idx_monthly_expense_year_month ON analysis_monthly_expense (year_month);

CREATE INDEX IF NOT EXISTS idx_consumption_pattern_user_id ON analysis_consumption_pattern (user_id);
CREATE INDEX IF NOT EXISTS idx_briefing_history_user_id ON analysis_ai_briefing_history (user_id);
CREATE INDEX IF NOT EXISTS idx_recommendation_user_id ON analysis_ai_recommendation (user_id);
CREATE INDEX IF NOT EXISTS idx_vector_metadata_user_id ON analysis_ai_vector_metadata (user_id);
